apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: clinical-database
type: Opaque
stringData:
  # Valores en texto claro que Kubernetes convertirá a base64 internamente.
  # En producción, reemplaza esto por secretos gestionados (Vault, SealedSecrets, etc.)
  JWT_SECRET: "Clinica-UAJS"
  # Si prefieres no exponer la contraseña en el ConfigMap ponla aquí en forma de secret
  DB_PASSWORD: "postgres"
