apiVersion: v1
kind: Service
metadata:
  name: backend-service-nodeport
  namespace: clinical-database
  annotations:
    note: "Service NodePort para pruebas locales. Usar solo en entornos de desarrollo."
spec:
  type: NodePort
  selector:
    app: backend-api
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      # nodePort: 30008  # opcional: descomenta para fijar el puerto
